### PR TITLE
Additions of docstrings and removal of small errors

### PR DESCRIPTION
**Pull request by bramvanwersch**
Added to some incomplete docstrings and removed some errors and unused parameters from functions.

### CODE REVIEW

**Comment by gamcil** [comment]
Cool, looks good!

Just two small things before I merge, both in https://github.com/gamcil/cblaster/pull/9/commits/7caa9801e58a5a0eb79472371f79a27acbfaa1b5. Can you double check that the linkage import from SciPy works fine without the import scipy line? I had trouble on my end with that which is why I put it there. Also, could you add the params back to `plot_session_file` - still want to be able to either save/serve from it, even if it isn't actually used anywhere.

Thanks!

**Comment by bramvanwersch** [comment]
I added the import back. I removed the arguments initially because they are not present in the base method from_json in the Serialiser class, meaning that if the function gets called the program would crash because serve and html are unused variables in that function. Regardless I added them back in as you requested but I think that the base from_json method should either have a **kwargs argument or add both these variables.

**Comment by gamcil** [comment]
Ohh you're right but it's a different crash. `plot_session_file` calls `plot_session` with those params, which have since been removed, resulting in a crash. So, changes should be: 

1. Change `plot_session_file` args to (path, output=None)
2. Change `plot_session` call inside `plot_session_file` to `plot_session(session, output=output)`

Also, could you remove the testing lines you added to main in https://github.com/gamcil/cblaster/pull/9/commits/e883313e839f7324906ce6ec8541ab99a5c0890a, then can merge.

**Comment by bramvanwersch** [comment]
I changed it, and my excuse for the testing change. I did not intend to commit that.

**Pull request merged**
