### PR TITLE
fix(remote): accommodated change in NCBI API

### PR DESCRIPTION
**Pull request by FriederikeBiermann**
The syntax to retrieve BLAST results changed recently, the retrieve function was modified to accommodate

### CODE REVIEW

**Comment by Clauvio** [comment]
Appreciate! It really works!

**Comment by raphenya** [comment]
Yes, this works! Thank you @FriederikeBiermann1

**Comment by drboothtj** [comment]
> The syntax to retrieve BLAST results changed recently, the retrieve function was modified to accommodate

Thanks for the fix. NCBI keep changing their API, it is a nightmare to stay on top of. I've asked Cam to take a look at the request!

Cheers!

**Comment by drboothtj** [comment]
> > The syntax to retrieve BLAST results changed recently, the retrieve function was modified to accommodate
> 
> Thanks for the fix. NCBI keep changing their API, it is a nightmare to stay on top of. I've asked Cam to take a look at the request!
> 
> Cheers!

Unfortunately, this doesn't solve all the problems as NCBI is also cutting of the results text if it is too long. If this fix doesn't work try reducing the size of the hit list (-hs)

**Comment by gamcil** [comment]
Thanks for the PR, merged and have made a new release.

**Pull request merged**
